### ISSUE TITLE
异常占用bug(没事干，发个Issues)

### ISSUE THREAD

**Issue by Herielmn** [xiaofeiyu0723/ExVR#4]
启动捕捉软件后，如果有游戏窗口最大化且置于焦点，软件CPU占用会由10%左右飙升至60%左右，同时手部捕捉延迟会提升至三到四秒
暂时解决方法: 将游戏调整为非最大化，将窗口大小拉大与最大化窗口无异即可暂时正常使用

**Comment by xiaofeiyu0723** [comment]
I will fix it as soon as possible

**Comment by xiaofeiyu0723** [comment]
The new release is updated, you can try it.

**Comment by xiaofeiyu0723** [comment]
Weirdly, I can not repeat this issue.

**Comment by xiaofeiyu0723** [comment]
I will update the priority adjustment list for people to choose from when encountering this situation
