### ISSUE TITLE
R菜单偏移问题(没事干，再发个Issues)

### ISSUE THREAD

**Issue by Herielmn** [xiaofeiyu0723/ExVR#5]
在使用R菜单时，滚轮选择按钮按下确认后会产生未知偏移，具体现象为按下该按钮会触发另一个按钮功能，常见于当按钮过多时，按钮过少时不易触发。经过多次测试后，确认偏移多数偏移到选择按钮附近的其他按钮，少部分偏移至随机其他按钮。
替代方案:使用浮动菜单模型功能按钮

**Comment by xiaofeiyu0723** [comment]
Thank you for your feedback. I will fix it.

**Comment by xiaofeiyu0723** [comment]
The new release is updated, you can try it.
