### ISSUE TITLE
Multiple cameras and Nvidia Broadcast virtual camera call problems | 多摄像头和Nvidia Broadcast虚拟摄像头调用问题

### ISSUE THREAD

**Issue by AuraElicase** [xiaofeiyu0723/ExVR#6]
# System Information
* OS: Windows 11 23H2 Build 22631.4391
* CPU: AMD Ryzen 9 5900HS with Radeon Graphics
* Memory: 16.0 GB
* GPU: NVIDIA GeForce RTX 3050ti Laptop
* Number of cameras: 10-11 (physical camera 2-3, virtual camera 8)
* Virtual Camera details: NDI Virtual Camera *4; OBS virtual camera *1; Other virtual cameras *2; NVIDIA Broadcast Virtual Camera *1

# Error details
1. The actual camera call is different from the display name
If you select the NDI virtual camera, the actual display is another virtual camera or physical camera.
![image](https://github.com/user-attachments/assets/c8327ba3-9b1c-47b6-9a9f-5bfacf263bde)
2. The NVIDIA Broadcast virtual camera captures a black screen or a display screen
![image](https://github.com/user-attachments/assets/1b240886-23df-4313-bc47-e3f365d3abe3)

# Temporary solution
Because the OBS virtual camera is work, the use of OBS to capture camera images and then pass the virtual camera into the software can temporarily avoid the problem, and the camera can be manually switched horizontally and vertically to capture more vertical parts.

---
# 系统信息  
* 操作系统：Windows 11 23H2 Build 22631.4391
* CPU：AMD Ryzen 9 5900HS with Radeon Graphics
* 内存：16.0 GB
* GPU：NVIDIA GeForce RTX 3050ti Laptop
* 摄像头数量：10-11（实体摄像头2-3，虚拟摄像头8）
* 虚拟摄像头详情：NDI虚拟摄像头*4；OBS虚拟摄像头*1；其他虚拟摄像头*2；NVIDIA Broadcast虚拟摄像头*1

# 错误详情信息  
1. 摄像头实际调用与显示名称不同
如选择NDI虚拟摄像头，实际显示是其他的虚拟摄像头画面或物理摄像头。
![image](https://github.com/user-attachments/assets/c8327ba3-9b1c-47b6-9a9f-5bfacf263bde)
2.   NVIDIA Broadcast虚拟摄像头捕获时黑屏或花屏
![image](https://github.com/user-attachments/assets/1b240886-23df-4313-bc47-e3f365d3abe3)

# 临时解决方案
因为OBS虚拟摄像头是正常工作的，因此采用OBS采集摄像头画面再通过虚拟摄像头传入软件可暂时规避问题，而且可以进行摄像头的手动横竖切换，以捕获到更多的垂直部位。

**Comment by xiaofeiyu0723** [comment]
Thank you for your detailed feedback. For the camera selection issue, I will fix it as soon as possible. For the second one, I think it's related to the OpenCV library, and I didn't find any solutions.

**Comment by Herielmn** [comment]
我觉得需要摄像头的索引日志来确定问题
I think we need an index log of the camera to determine the problem.
