### ISSUE TITLE
联想拯救者电脑系列占用与卡顿问题 | Lenovo Legion PC Series Occupancy and Lagging Issues

### ISSUE THREAD

**Issue by Herielmn** [xiaofeiyu0723/ExVR#9]
电脑品牌: 联想拯救者y7000p2024
CPU: i7-14650HX
独立显卡: NVIDIA GeForce RTX 4060 Laptop GPU
系统：Windows 11 专业版 23H2
问题描述:
打开显卡混合模式时：启动软件与游戏并开启追踪，将游戏窗口最大化时，软件在后台CPU占用会异常提升
              临时解决方法：1.关闭最大化，拉大游戏窗口游玩.    2.打开独显直连(但会导致另一个问题)
打开显卡独显直连时：启动软件与游戏并开启追踪，将游戏窗口置于焦点时，软件对于摄像头视频帧捕捉会有明显的卡顿，造成追踪卡顿
              临时解决方法：暂未发现

**Comment by Herielmn** [comment]
初步怀疑是拯救者系列的调度问题

**Comment by xiaofeiyu0723** [comment]
You can select the lower priority in the interface of the new version program.
